### ISSUE TITLE
Live Preview instructions

### ISSUE THREAD

**Issue by stevewyres** [contentstack/contentstack-dotnet#16]
Hi

Trying to implement the LivePreview using the SDK, but not sure where to start.  Are there any simple instructions on how to get a .NET website to use LivePreview using the SDK.  

I can see the LivePreviewConfig, but not sure when to populate, for example only if ContentStack calls the code, so using a header?

Thanks

**Comment by uttamukkoji** [comment]
Hi @stevewyres ,

Here is doc for configuring .Net SDK with Live preview: https://www.contentstack.com/docs/developers/dot-net/get-started-with-dot-net-sdk-and-live-preview

Let us know if this helps you resolve the issue you are facing. If not, please connect with us on support@contentstack.com this will help us to identify issue personally.
