### ISSUE TITLE
Newtonsoft.Json is Deprecated

### ISSUE THREAD

**Issue by Eliza-Huang** [contentstack/contentstack-dotnet#56]
Newtonsoft.Json has been deprecated by Microsoft in .NET Core 3.0. There are other much more performant JSON processing libraries, the recommendation is System.Text.Json https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/migrate-from-newtonsoft

We are reluctant to use this SDK since it has such a performance hit using the deprecated library and would consider using it if it was switched to something more performant.

**Comment by Eliza-Huang** [comment]
We are considering building a .NET service that grabs content from Contentstack. But we are leaning towards using the GraphQL endpoint since Newtonsoft.Json is a performance hit. We were wondering if there's a plan to update that to System.Text.Json?

**Comment by Eliza-Huang** [comment]
Just a heads up, we may still not use this if Newtonsoft.Json is removed, just calling this out as it is deprecated.

**Comment by nadeem-cs** [comment]
Thanks for the heads up @Eliza-Huang ! We haven't scoped this yet but we are aware that System.Text.Json is comparatively faster than Newtonsoft.Json and we will discuss internally on how we can make the shift.
